# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KitchenAppGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 582)
        MainWindow.setStyleSheet("background-color: rgb(17, 17, 18)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 71, 581))
        self.frame.setStyleSheet("background-color: rgb(14, 13, 14)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui_images/home_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 71, 71))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui_images/Table5_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 140, 71, 71))
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui_images/save_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 210, 71, 71))
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui_images/download_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 0, 731, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.label = QtWidgets.QLabel(self.homePage)
        self.label.setGeometry(QtCore.QRect(0, 0, 721, 191))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(112, 0, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.homePage)
        self.tablePage = QtWidgets.QWidget()
        self.tablePage.setStyleSheet("")
        self.tablePage.setObjectName("tablePage")
        self.tableWidget = QtWidgets.QTableWidget(self.tablePage)
        self.tableWidget.setGeometry(QtCore.QRect(0, 120, 731, 361))
        self.tableWidget.setStyleSheet("QHeaderView::section { background-color:RGB(17,17,18);color: rgb(112, 0, 255)}")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(243)
        self.label_2 = QtWidgets.QLabel(self.tablePage)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tablePage)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 480, 71, 71))
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui_images/plus_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tablePage)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 480, 71, 71))
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui_images/minus_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.tablePage)
        self.AddItemPage = QtWidgets.QWidget()
        self.AddItemPage.setObjectName("AddItemPage")
        self.label_3 = QtWidgets.QLabel(self.AddItemPage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.AddItemPage)
        self.textEdit.setGeometry(QtCore.QRect(220, 210, 281, 41))
        self.textEdit.setStyleSheet("background-color: rgb(14, 13, 14)")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.AddItemPage)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 260, 281, 41))
        self.textEdit_2.setStyleSheet("background-color: rgb(14, 13, 14)")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.AddItemPage)
        self.textEdit_3.setGeometry(QtCore.QRect(220, 310, 281, 41))
        self.textEdit_3.setStyleSheet("background-color: rgb(14, 13, 14)")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_4 = QtWidgets.QLabel(self.AddItemPage)
        self.label_4.setGeometry(QtCore.QRect(150, 220, 61, 21))
        self.label_4.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.AddItemPage)
        self.label_5.setGeometry(QtCore.QRect(150, 270, 61, 21))
        self.label_5.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.AddItemPage)
        self.label_6.setGeometry(QtCore.QRect(150, 320, 61, 21))
        self.label_6.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.AddItemPage)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 390, 71, 71))
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.AddItemPage)
        self.removePage = QtWidgets.QWidget()
        self.removePage.setObjectName("removePage")
        self.label_7 = QtWidgets.QLabel(self.removePage)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.removePage)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 450, 71, 71))
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.scrollArea = QtWidgets.QScrollArea(self.removePage)
        self.scrollArea.setGeometry(QtCore.QRect(20, 120, 681, 321))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 664, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.removePage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to Kitchen Assistant"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expiration"))
        self.label_2.setText(_translate("MainWindow", "Table View"))
        self.label_3.setText(_translate("MainWindow", "ADD ITEM"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Quantity"))
        self.label_6.setText(_translate("MainWindow", "Expiration"))
        self.label_7.setText(_translate("MainWindow", "Remove Item(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
