# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KitchenAppGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 532)
        MainWindow.setStyleSheet("background-color: rgb(17, 17, 18)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 71, 581))
        self.frame.setStyleSheet("background-color: rgb(14, 13, 14)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.homeButton = QtWidgets.QPushButton(self.frame)
        self.homeButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui_images/home_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("gui_images/home_color.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(50, 50))
        self.homeButton.setObjectName("homeButton")
        self.dataButton = QtWidgets.QPushButton(self.frame)
        self.dataButton.setGeometry(QtCore.QRect(0, 70, 71, 71))
        self.dataButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui_images/Table5_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dataButton.setIcon(icon1)
        self.dataButton.setIconSize(QtCore.QSize(50, 50))
        self.dataButton.setObjectName("dataButton")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(0, 140, 71, 71))
        self.saveButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui_images/save_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon2)
        self.saveButton.setIconSize(QtCore.QSize(50, 50))
        self.saveButton.setObjectName("saveButton")
        self.downloadButton = QtWidgets.QPushButton(self.frame)
        self.downloadButton.setGeometry(QtCore.QRect(0, 210, 71, 71))
        self.downloadButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui_images/download_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon3)
        self.downloadButton.setIconSize(QtCore.QSize(50, 50))
        self.downloadButton.setObjectName("downloadButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 0, 731, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.welcomeLabel = QtWidgets.QLabel(self.homePage)
        self.welcomeLabel.setGeometry(QtCore.QRect(0, 0, 721, 191))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(112, 0, 255)")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.stackedWidget.addWidget(self.homePage)
        self.tablePage = QtWidgets.QWidget()
        self.tablePage.setStyleSheet("")
        self.tablePage.setObjectName("tablePage")
        self.tableWidget = QtWidgets.QTableWidget(self.tablePage)
        self.tableWidget.setGeometry(QtCore.QRect(0, 120, 731, 361))
        self.tableWidget.setStyleSheet("QHeaderView::section { background-color:RGB(17,17,18);color: rgb(112, 0, 255)}")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(243)
        self.label_2 = QtWidgets.QLabel(self.tablePage)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.addButton = QtWidgets.QPushButton(self.tablePage)
        self.addButton.setGeometry(QtCore.QRect(150, 480, 71, 71))
        self.addButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui_images/plus_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon4)
        self.addButton.setIconSize(QtCore.QSize(50, 50))
        self.addButton.setObjectName("addButton")
        self.removeButton = QtWidgets.QPushButton(self.tablePage)
        self.removeButton.setGeometry(QtCore.QRect(480, 480, 71, 71))
        self.removeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui_images/minus_color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon5)
        self.removeButton.setIconSize(QtCore.QSize(50, 50))
        self.removeButton.setObjectName("removeButton")
        self.stackedWidget.addWidget(self.tablePage)
        self.AddItemPage = QtWidgets.QWidget()
        self.AddItemPage.setObjectName("AddItemPage")
        self.label_3 = QtWidgets.QLabel(self.AddItemPage)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.NameTextEdit = QtWidgets.QTextEdit(self.AddItemPage)
        self.NameTextEdit.setGeometry(QtCore.QRect(220, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.NameTextEdit.setFont(font)
        self.NameTextEdit.setStyleSheet("background-color: rgb(14, 13, 14);\n"
"color: rgb(255, 255, 255)")
        self.NameTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.NameTextEdit.setObjectName("NameTextEdit")
        self.QuantityTextEdit = QtWidgets.QTextEdit(self.AddItemPage)
        self.QuantityTextEdit.setGeometry(QtCore.QRect(220, 260, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.QuantityTextEdit.setFont(font)
        self.QuantityTextEdit.setStyleSheet("background-color: rgb(14, 13, 14);\n"
"color: rgb(255,255,255)")
        self.QuantityTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.QuantityTextEdit.setObjectName("QuantityTextEdit")
        self.ExpireTextEdit = QtWidgets.QTextEdit(self.AddItemPage)
        self.ExpireTextEdit.setGeometry(QtCore.QRect(220, 310, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExpireTextEdit.setFont(font)
        self.ExpireTextEdit.setStyleSheet("background-color: rgb(14, 13, 14);\n"
"color: rgb(255,255,255)")
        self.ExpireTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ExpireTextEdit.setObjectName("ExpireTextEdit")
        self.NameLabel = QtWidgets.QLabel(self.AddItemPage)
        self.NameLabel.setGeometry(QtCore.QRect(150, 220, 61, 21))
        self.NameLabel.setStyleSheet("color: rgb(112, 0, 255)")
        self.NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel.setObjectName("NameLabel")
        self.QuantityLabel = QtWidgets.QLabel(self.AddItemPage)
        self.QuantityLabel.setGeometry(QtCore.QRect(150, 270, 61, 21))
        self.QuantityLabel.setStyleSheet("color: rgb(112, 0, 255)")
        self.QuantityLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.QuantityLabel.setObjectName("QuantityLabel")
        self.expirationLabel = QtWidgets.QLabel(self.AddItemPage)
        self.expirationLabel.setGeometry(QtCore.QRect(150, 320, 61, 21))
        self.expirationLabel.setStyleSheet("color: rgb(112, 0, 255)")
        self.expirationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.expirationLabel.setObjectName("expirationLabel")
        self.AddItemButton = QtWidgets.QPushButton(self.AddItemPage)
        self.AddItemButton.setGeometry(QtCore.QRect(330, 390, 71, 71))
        self.AddItemButton.setText("")
        self.AddItemButton.setIcon(icon4)
        self.AddItemButton.setIconSize(QtCore.QSize(50, 50))
        self.AddItemButton.setObjectName("AddItemButton")
        self.stackedWidget.addWidget(self.AddItemPage)
        self.removePage = QtWidgets.QWidget()
        self.removePage.setObjectName("removePage")
        self.label_7 = QtWidgets.QLabel(self.removePage)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 721, 111))
        font = QtGui.QFont()
        font.setFamily("Muna")
        font.setPointSize(39)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(112, 0, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.removePage)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 450, 71, 71))
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.scrollArea = QtWidgets.QScrollArea(self.removePage)
        self.scrollArea.setGeometry(QtCore.QRect(20, 120, 681, 321))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 664, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.removePage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeLabel.setText(_translate("MainWindow", "Welcome to Kitchen Assistant"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expiration"))
        self.label_2.setText(_translate("MainWindow", "Table View"))
        self.label_3.setText(_translate("MainWindow", "ADD ITEM"))
        self.NameLabel.setText(_translate("MainWindow", "Name"))
        self.QuantityLabel.setText(_translate("MainWindow", "Quantity"))
        self.expirationLabel.setText(_translate("MainWindow", "Expiration"))
        self.label_7.setText(_translate("MainWindow", "Remove Item(s)"))
